name: Release NuGet

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: danyolgiax/DevOps.Templates/.github/workflows/nuget-build.yml@main

  publish:
    needs: build
    uses: danyolgiax/DevOps.Templates/.github/workflows/nuget-publish.yml@main
    secrets:
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}